### PR TITLE
Updated initramfs/Makefile to check for 'cpio' -- Cleaner vm/Makefile

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by perror — COMMENTED** [review]
The `vm/start.sh` is specific to an architecture, so there is no need to customize such things as it will never change.

**Review by perror — COMMENTED** [review]
This is very unlikely but this is true that I should check for it. The problem here is that you pull request against the branch `kernel-5.2-x86_64` and it should be added to `master`.

**Comment by perror** [comment]
I merge the check of `cpio` into `master`. I think the other patches can be safely dropped.

**Comment by ghost** [comment]
I was missing cpio that's why I added a check in the Makefile, to spare time for other students.

**Pull request closed without merging**
